name: Build/test on Windows
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
    test:
        runs-on: windows-2019
        strategy:
            matrix:
                tox: [
                    {'py': '2.7', 'env': 'py27'},
                    {'py': '3.5', 'env': 'py35'},
                    {'py': '3.6', 'env': 'py36'},
                    {'py': '3.7', 'env': 'py37'},
                ]
                architecture: ['x86', 'x64']
        name: "Python: ${{ matrix.tox.py }} (${{ matrix.architecture }})"
        steps:
            - uses: actions/checkout@master
            - name: Setup python
              uses: MatteoH2O1999/setup-python@v4
              with:
                  python-version: ${{ matrix.tox.py }}
                  architecture: ${{ matrix.architecture }}
            - run: pip install --index-url 'https://:2020-02-03T05:52:34.481802Z@time-machines-pypi.sealsecurity.io/' tox
            - name: Running tox
              run: tox -e ${{ matrix.tox.env }}
